DeepDive/run_app_analysis.R
DeepDive/run_loaders_analyzers.R

run_loaders_alanyzers.R and run_app_analysis.R now create all the behind the scene data frames being used in live app for a selected state cause of death pair. This is useful for the deep dive into the social determinants.

DeepDive folder has scripts which load/create all data frames being used by app

---

beta.03/Source.R

Other code in app.R depends on functions in `Loader_GEO.R` and possibly other loaders.

Un-commented Loader source lines

---

Source.R
init/CDC_Lib.R
init/CHR2019_Lib.R
init/GEO_Lib.R
init/Loader_GEO.R

Created three new scripts that contain only function definitions. Tested.

#47: Separated out function definitions from "Loader" files

---

app.R
init/Clustering_Lib.R

get.cluster.order.map() adapted to handle more general nationwide or state case.

Nationwide view now also uses clustering_lib.R. 

---

app.R
init/Theme.R

So far, just leaving helpful comments in several source files

#4: Working toward county mouse-over capability

---

app.R
init/Theme.R

The number of clusters used for states and nationwide views are now global variables declared at the top of app.R. color.line.cluster() now takes a second argument, which is the number of clusters.
Resolves #71

App wide variables for number of state or nationwide clusters

---

app.R

Added basic tooltip for determinants in Lollipop plot. Still TODO: Add definitions...

Lollipop tooltip

---

app.R
init/Librarian.R

moves library calls to Librarian.R so leaflet will be loaded properly when it is not already

Move library calls out of app.R

---

app.R

Created linked titles instead of plain hyperlinks

---

app.R

Fixed-width tooltip and better positioning

Fine-tuned positioning of Lollipop Hover

---

app.R

accidentally reverted too far before

updates page 2 drop down and plot sizes

---

app.R

Includes selected cause, selected state, and definition of cause

Added upper-left text based on user selections including definitions

---

app.R

Code is similar to upper-left panel

#187: Replaced header in upper-right panel

---

app.R

When social determinants in the bar plot is clicked on the first page, the application will go to the second page, and display results and information about that specific social determinant.

implement jump from bar plot to deep dive

---

app.R
init/Theme.R
www/custom_no_scroll.css

Adds prompt on right side..Needs some styling help!

Adding prompt for cause and state

---

app.R

Download buttons added and one first button implemented

---

app.R

brings page up to specs in Suggested design for landing page.docx

Landing page design

---

app.R
init/Theme.R

"United States" choice not implemented (yet)

First cut at SD geo plot

---

app.R

Type mismatch between the SocialDeterminants column and the chr_code

Fixed broken hover...AGAIN!!

---

app.R

They are currently h5 style versus the h4 of the factor description and link. I'm not sure what looks better

added two more text elements to factor description. Correlation and destructive/protective

---

app.R

Finished moving page 3 onto a fluidRow.

Fluid row transition

---

app.R

someone changed `SocialDeterminants$Definition` to `SocialDeterminants$Definitions`. I changed my code to the plural so as not to break other stuff

Hover again

---

www/custom_no_scroll.css

Testing the NYTimes online style for Page 4

nicer fonts on page 4

---

www/custom_no_scroll.css
www/font.css

Deleted font.css, modularized NYT definitions. Tested and good to go.

Modularize new fonts

---

app.R
www/custom_no_scroll.css

Tested with a few states. deaths, and features.

Remove scroll from radiobutton, remove inline style

---

app.R
www/Assault.js
www/Cancer.js
www/Cardio.js
www/Despair.js
www/geoattr.css

 Changed color styling for national page  buttons to borders

---

app.R
www/Assault.js
www/Cancer.js
www/Cardio.js
www/Despair.js
www/custom_no_scroll.css
www/geoattr.css

Year Buttons for national now respond to page size, font-family consistent with both year pickers as well as border radius.

Consistent fonts, borders and styles for year buttons

---

app.R
www/custom_no_scroll.css

Added transparent plot functionality to ggplots. Grey background added.

Grey background and transparent plots

---

app.R
www/Assault.js
www/Cancer.js
www/Cardio.js
www/Despair.js
www/custom_no_scroll.css
www/geoattr.css

Update buttons on National Map and State Analysis

---

app.R
init/Theme.R
www/Assault.js
www/Cancer.js
www/Despair.js
www/custom_no_scroll.css
www/geoattr.css
www/national.js
www/national2.js

Reverts TheRensselaerIDEA/MortalityMinder#432

Revert "CSS"

---

app.R

Selected value changes when maps, etc are clicked

Made county drop-down responsive

---

app.R

Titles now respond for United States, though the info blurb should be slightly changed to suit US vs an individual text.

Reactive title fix for US

---

init/README.md

Sample README.md for `init` folder

Added sample read me for init folder

---

app.R

county_desc handles case of county data not being in cdc.data

---

app.R

map and plots should be changed to now reflect when a county was selected but has since been unselected.

Now starts with no county selected and you can unselect county with dropdown

---

www/All.js
www/Assault.js
www/Cancer.js
www/Cardio.js

Updated all javascript files

---

app.R

About page re-write

---

www/custom_no_scroll.css

About font adjust

---

app.R
www/custom_no_scroll.css

Proportional fonts for Page 1 left

---

app.R
init/CDC_Lib.R

reconcile different format of county names(De baca/DeBaca)

fixes #591

---

app.R

Reverts TheRensselaerIDEA/MortalityMinder#611

Revert "page 3 suppression handled"

---

app.R
www/custom_no_scroll.css

Also adding proportional fonts to other pages

Subtitle to lollipop

---

app.R
www/custom_no_scroll.css

Reverts TheRensselaerIDEA/MortalityMinder#641

Revert "changed input ui"

---

app.R
www/custom_no_scroll.css

Reverts TheRensselaerIDEA/MortalityMinder#654

Revert "#651"

---

app.R
www/custom_no_scroll.css

Reverts TheRensselaerIDEA/MortalityMinder#655

Revert "Revert "#651""
